updating header links and header styling
Financial-Times/o-header--theme-ic pull request #1
Opened 2016-11-25 11:56 UTC by eddichen

2016-11-25 11:59 UTC, alicebartlett approved these changes

2016-11-28 10:08 UTC, alicebartlett requested changes

2016-11-28 10:08 UTC, alicebartlett commented on src/scss/investors_chronicle_theme.scss
> +			background-image: url('https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fnew.investorschronicle.co.uk%2Fbundles%2Fapp%2Fimages%2Flogo-investors-chronicle.svg?url=https%253A%25
I don't think you need the ?url parameter here

2016-12-06 11:55 UTC, eddichen commented on src/scss/investors_chronicle_theme.scss
> +			background-image: url('https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fnew.investorschronicle.co.uk%2Fbundles%2Fapp%2Fimages%2Flogo-investors-chronicle.svg?url=https%253A%25
this has been updated

2016-12-14 16:00 UTC, alicebartlett approved these changes

2016-12-14 16:40 UTC, merged